# Site settings
title: Mini Marsiah
email: marsiah30@gmail.com
url: https://minimarsiah.github.io
description: "Nim 11453201774
              Jurusan Sistem Informasi
              Fakultas Sains dan Teknologi."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://instagram.com/minimarsiah
  - title: facebook
    url: http://facebook.com/minimarsiah
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
